# Generated by Django 3.0.8 on 2020-07-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0004_auto_20200731_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseunit',
            name='tenant_id_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='tenant_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
