# Generated by Django 3.0.8 on 2020-09-29 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0005_auto_20200731_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('month', models.DateField()),
                ('name_of_payer', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paid', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=19)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental_houses.Building')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental_houses.HouseUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
