# Generated by Django 3.0.8 on 2020-09-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200929_1956'),
        ('rental_houses', '0006_auto_20200929_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client'),
        ),
    ]
