# Generated by Django 3.0.8 on 2020-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0007_auto_20200929_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungallow', 'Bungalow'), ('other', 'Other')], max_length=20),
        ),
    ]
