# Generated by Django 3.0.8 on 2020-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0008_auto_20200930_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='building',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='year',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='month',
            field=models.PositiveIntegerField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1),
        ),
    ]
