# Generated by Django 3.0.8 on 2020-10-05 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20200930_2034'),
        ('rental_houses', '0009_auto_20200930_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('expense_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(max_length=50, null=True)),
                ('date_paid', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('premises_type', models.CharField(choices=[('residential', 'Residential eg family houses, bedsitters'), ('educational', 'Educational eg schools, colleges'), ('institutional', 'Institutional eg churches, hospitals'), ('business', 'Business eg offices, banks, courthouses'), ('mercantile', 'Mercantile eg shops, stores, showrooms'), ('industrial', 'Industrial eg assembly plants, manufacturing')], max_length=20)),
                ('building_type', models.CharField(choices=[('storey', 'Storey'), ('bungalow', 'Bungalow'), ('other', 'Other')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('cube', 'Cube'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('four_bedroom', 'Four Bedroom'), ('five_bedroom', 'Five Bedroom'), ('shop', 'Shops')], max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tenant_id_no', models.IntegerField(blank=True, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('tenant_email', models.EmailField(max_length=250)),
                ('premises', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_houses.Premises')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='houseunit',
            name='building',
        ),
        migrations.RenameField(
            model_name='rentpayment',
            old_name='name_of_payer',
            new_name='payer_name',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='currency',
            field=models.CharField(choices=[('KSH', 'Kenya Shillings'), ('USD', 'US Dollars')], default='cash', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='payer_national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'Mpesa'), ('bank', 'Bank')], default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='year',
            field=models.PositiveIntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021')], default=2020, null=True),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='premises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_houses.Premises'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental_houses.Unit'),
        ),
        migrations.DeleteModel(
            name='HouseUnit',
        ),
    ]
