# Generated by Django 3.0.8 on 2020-10-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0010_auto_20201005_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentpayment',
            old_name='house',
            new_name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('premises', 'unit_number')},
        ),
    ]
