# Generated by Django 3.0.8 on 2020-10-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0011_auto_20201006_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payer_phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
