# Generated by Django 3.0.8 on 2020-12-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_houses', '0013_rentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaccount',
            name='name',
        ),
    ]
