# Generated by Django 3.0.8 on 2020-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
