# Generated by Django 3.0.8 on 2020-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200929_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
